[book]
authors = ["Oxide CI Maintainers"]
language = "en"
src = "src"
title = "Oxide CI Documentation"

[output.html]
git-repository-url = "https://github.com/copyleftdev/oxide-ci"
edit-url-template = "https://github.com/copyleftdev/oxide-ci/edit/main/docs/{path}"
site-url = "/oxide-ci/"
additional-css = ["theme/css/custom.css"]

